version: 2

workflows:
  version: 2
  build:
    jobs:
      - build-node8
      - build-node12

jobs:
  build-node8: &base
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  build-node12:
    <<: *base
    docker:
      - image: circleci/node:12
